services:
  - type: web
    name: jp-home-inspections
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: out
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
